### ISSUE TITLE
[FEATURE]: LED support as user feedback

### ISSUE THREAD

**Issue by frunika** [PhotoboothProject/photobooth#664]
### Is your feature request related to a problem?

Yes

### Description

Using LEDs to give feedback to the users could be a nice feature. Already one LED could give some useful information, especially when no screen/tablet is connected. A RGB LED or multiple LEDs could be even more useful.

### Describe the solution you'd like

Configuring LED GPIO in the backend and pair them with an "action". First actions could be "taking a photo" or "waiting for button press". The LEDs start blinking/pulsing/being on if the action is called. If an action is finished the corresponding LEDs returns to a default state.

### Describe alternatives you've considered

none... 🤣

**Comment by andi34** [comment]
Hey and thanks for your request. Some light controllers are possible already. Sadly the sysfs we use on Remotebuzzer-Server makes trouble actually because the Pi Foundation changed the sysfs values on 6.6 Kernel for ALL Raspberry Pi. Besides that the sysfs is deprecated. 
Advanced user can adjust those values inside the admin panel and /boot/firmware/config.txt
Right values can be found out typing `cat /sys/kernel/debug/gpio`.

In case the sysfs was disabled completely (also possible) , only a kernel downgrade to 6.1 would make the feature useable.

It's an decision of the Pi Foundation making the Remotebuzzer Server an experimental feature soon because we can't add default values and the user must take care.

In long term: the Remotebuzzer Server must be rewritten in python to be able to use other libraries instead of the deprecated sysfs... Might take until end of the year.
