### ISSUE TITLE
[BUG]: Language files not registered

### ISSUE THREAD

**Issue by mgineer85** [PhotoboothProject/photobooth#81]
### Describe the bug

Problem loading language files:
![grafik](https://user-images.githubusercontent.com/3868450/200165693-5d888bdf-d6b6-4af3-b17b-de449e3f2d68.png)

### Steps to reproduce the behavior

1 Fresh installation, new OS, starting with installation script
2 Photobooth was installed to subdirectory, so accessible by http://photobooth/photobooth
3 Find language files are always loaded from root directory instead subdirectory.

### Expected behavior

Load language files from subdirectory where installed by script.

### Photobooth Version

yesterday

### Did it work before?

Yes

**Comment by andi34** [comment]
@mgrl the path is detected automatically, but it can be adjusted via adminpanel in case the detection of the path fails (e.g. because of wrong / special Webserver settings). Last time I've heard about that was because of a wrong defined document_root path which is used to detect the install path (`$_SERVER['DOCUMENT_ROOT'];`).

**Comment by andi34** [comment]
![Screenshot_20221106-123721](https://user-images.githubusercontent.com/6080900/200168310-89c9cee9-cb58-496a-bdc5-1fc52a2d126e.png)

**Comment by mgineer85** [comment]
I see. Good to know which setting to change. It's been complete fresh installation, latest RPI OS. Not sure why the autodetection might have failed.
Think it can be closed then.
